### ISSUE TITLE
Cannot install 1.0.* from composer

### ISSUE THREAD

**Issue by netounet** [opensky/OpenSkyRuntimeConfigBundle#20]
Cannot install anymore from composer 

Try this : 
"opensky/runtime-config-bundle": "1.0.*@dev"
"opensky/runtime-config-bundle": "1.0.x-dev"

> The requested package opensky/runtime-config-bundle could not be found in any version . . .

Thks in advance for your reply

**Comment by pharv** [comment]
Just updated packagist.  Try again now.

**Comment by netounet** [comment]
thks ! works with ~1.0 tag
